# Generated by Django 4.2.21 on 2025-05-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avto', '0002_phone_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
